apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book-frontend
  template:
    metadata:
      labels:
        app: book-frontend
    spec:
      containers:
        - name: book-frontend
          image: hafsah002/book-management-frontend:latest
          ports:
            - containerPort: 80 