apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book-web
  template:
    metadata:
      labels:
        app: book-web
    spec:
      containers:
        - name: book-backend
          image: hafsah002/book-management-backend:latest
          ports:
            - containerPort: 5555
          env:
            - name: MONGO_URL
              value: "mongodb://mongo:27017/bookdb"
            - name: JWT_SECRET
              value: "mySuperSecretJWTKey123"
        - name: book-frontend
          image: yourdockerhubusername/book-management-frontend:latest
          ports:
            - containerPort: 80 